GRANT ALL ON SCHEMA public TO "_master_admin";
SET SESSION AUTHORIZATION "_master_admin";

DROP VIEW IF EXISTS public.v_app_salys;
DROP TABLE IF EXISTS public.salys;

CREATE TABLE public.salys (
    iso3 char(3) NOT NULL,
    iso2 char(2) NOT NULL,
    name varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    capital varchar(255) NOT NULL,
    eng varchar(255) NOT NULL,
    eu bool,
    search varchar(255),
    PRIMARY KEY (iso3)
);


INSERT INTO public.salys(name,title,iso2,iso3,capital,eng) VALUES
('Afganistanas','Afganistano Islamo Respublika','AF','AFG','Kabulas','Afghanistan'),
('Airija','Airija','IE','IRL','Dublinas','Ireland'),
('Albanija','Albanijos Respublika','AL','ALB','Tirana','Albania'),
('Alžyras','Alžyro Liaudies Demokratine Respublika','DZ','DZA','Alžyras','Algeria'),
('Andora','Andoros Kunigaikštyste','AD','AND','Andora','Andorra'),
('Angola','Angolos Respublika','AO','AGO','Luanda','Angola'),
('Antigva ir Barbuda','Antigva ir Barbuda','AG','ATG','Sent Džonsas','Antigua and Barbuda'),
('Argentina','Argentinos Respublika','AR','ARG','Buenos Aires','Argentina'),
('Armenija','Armenijos Respublika','AM','ARM','Jerevanas','Armenia'),
('Australija','Australija','AU','AUS','Kanbera','Australia'),
('Austrija','Austrijos Respublika','AT','AUT','Víena','Austria'),
('Azerbaidžanas','Azerbaidžano Respublika','AZ','AZE','Baku','Azerbaijan'),
('Bahamos','Bahamų Sandrauga','BS','BHS','Nasau','Bahamas'),
('Bahreinas','Bahreino Karalyste','BH','BHR','Menama','Bahrain'),
('Baltarusija, Gudija','Baltarusijos Respublika','BY','BLR','Minskas','Belarus'),
('Bangladešas','Bangladešo Liaudies Respublika','BD','BGD','Daka','Bangladesh'),
('Barbadosas','Barbadosas','BB','BRB','Bridžtaunas','Barbados'),
('Belgija','Belgijos Karalyste','BE','BEL','Briuselis','Belgium'),
('Belizas','Belizas','BZ','BLZ','Belmopanas','Belize'),
('Beninas','Benino Respublika','BJ','BEN','Porto Novas','Benin'),
('Bisau Gvineja','Bisau Gvinejos Respublika','GW','GNB','Bisau','Guinea-Bissau'),
('Bolivija','Bolivijos Daugiataute Valstybe','BO','BOL','La Pasas / Sukrė','Bolivia'),
('Bosnija ir Hercegovina','Bosnija ir Hercegovina','BA','BIH','Sarajevas','Bosnia and Herzegovina'),
('Botsvana','Botsvanos Respublika','BW','BWA','Gaboronas','Botswana'),
('Brazilija','Brazilijos Federacine Respublika','BR','BRA','Brazilija','Brazil'),
('Brunejus','Brunejaus Darusalamas','BN','BRN','Bandar Seri Begavanas','Brunei Darussalam'),
('Bulgarija','Bulgarijos Respublika','BG','BGR','Sofija','Bulgaria'),
('Burkina Fasas','Burkina Fasas','BF','BFA','Uagadugu','Burkina Faso'),
('Burundis','Burundžio Respublika','BI','BDI','Gitega','Burundi'),
('Butanas','Butano Karalyste','BT','BTN','Timpu','Bhutan'),
('Centrines Afrikos Respublika','Centrines Afrikos Respublika','CF','CAF','Bangis','Central African Republic'),
('Čadas','Čado Respublika','TD','TCD','Ndžamena','Chad'),
('Čekija','Čekijos Respublika','CZ','CZE','Praha','Czechia'),
('Čile','Čiles Respublika','CL','CHL','Santjagas','Chile'),
('Danija','Danijos Karalyste','DK','DNK','Kopenhaga','Denmark'),
('Dominika','Dominikos Sandrauga','DM','DMA','Rozo','Dominica'),
('Dominikos Respublika','Dominikos Respublika','DO','DOM','Santo Domingas','Dominican Republic'),
('Dramblio Kaulo Krantas','Dramblio Kaulo Kranto Respublika','CI','CIV','Jamusukras','Côte d''Ivoire'),
('Džibutis','Džibučio Respublika','DJ','DJI','Džibutis','Djibouti'),
('Egiptas','Egipto Arabų Respublika','EG','EGY','Kairas','Egypt'),
('Ekvadoras','Ekvadoro Respublika','EC','ECU','Kitas','Ecuador'),
('Eritreja','Eritrejos Valstybe','ER','ERI','Asmara','Eritrea'),
('Estija','Estijos Respublika','EE','EST','Talinas','Estonia'),
('Esvatinis','Esvatinio Karalyste','SZ','SWZ','Mbabane / Lobamba','Eswatini'),
('Etiopija','Etiopijos Federacine Demokratine Respublika','ET','ETH','Adis Abeba','Ethiopia'),
('Fidžis','Fidžio Respublika','FJ','FJI','Suva','Fiji'),
('Filipinai','Filipinų Respublika','PH','PHL','Manila','Philippines'),
('Gabonas','Gabono Respublika','GA','GAB','Librevilis','Gabon'),
('Gajana','Gajanos Kooperacine Respublika','GY','GUY','Džordžtaunas','Guyana'),
('Gambija','Gambijos Respublika','GM','GMB','Bandžulis','Gambia'),
('Gana','Ganos Respublika','GH','GHA','Akra','Ghana'),
('Graikija','Graikijos Respublika','GR','GRC','Atėnai','Greece'),
('Grenada','Grenada','GD','GRD','Sent Džordžas','Grenada'),
('Gvatemala','Gvatemalos Respublika','GT','GTM','Gvatemala','Guatemala'),
('Gvineja','Gvinejos Respublika','GN','GIN','Konakris','Guinea'),
('Haitis','Haičio Respublika','HT','HTI','Port o Prensas','Haiti'),
('Hondūras','Hondūro Respublika','HN','HND','Tegusigalpa','Honduras'),
('Indija','Indijos Respublika','IN','IND','Naujasis Delis','India'),
('Indonezija','Indonezijos Respublika','ID','IDN','Džakarta','Indonesia'),
('Irakas','Irako Respublika','IQ','IRQ','Bagdadas','Iraq'),
('Iranas','Irano Islamo Respublika','IR','IRN','Teheranas','Iran'),
('Islandija','Islandija','IS','ISL','Reikjavikas','Iceland'),
('Ispanija','Ispanijos Karalyste','ES','ESP','Madridas','Spain'),
('Italija','Italijos Respublika','IT','ITA','Roma','Italy'),
('Izraelis','Izraelio Valstybe','IL','ISR','Jeruzalė / Tel Avivas','Israel'),
('Jamaika','Jamaika','JM','JAM','Kingstonas','Jamaica'),
('Japonija','Japonija','JP','JPN','Tokijas','Japan'),
('Jemenas','Jemeno Respublika','YE','YEM','Sana','Yemen'),
('Jordanija','Jordanijos Hašimitų Karalyste','JO','JOR','Amanas','Jordan'),
('Jungtine Karalyste','Jungtine Didžiosios Britanijos ir Šiaures Airijos Karalyste','UK','GBR','Londonas','United Kingdom of Great Britain and Northern Ireland'),
('Jungtines Valstijos, JAV','Jungtines Amerikos Valstijos','US','USA','Vašingtonas','United States of America'),
('Jungtiniai Arabų Emyratai','Jungtiniai Arabų Emyratai','AE','ARE','Abu Dabis','United Arab Emirates'),
('Juodkalnija','Juodkalnija','ME','MNE','Podgorica','Montenegro'),
('Kambodža','Kambodžos Karalyste','KH','KHM','Pnompenis','Cambodia'),
('Kamerūnas','Kamerūno Respublika','CM','CMR','Jaundė','Cameroon'),
('Kanada','Kanada','CA','CAN','Otava','Canada'),
('Kataras','Kataro Valstybe','QA','QAT','Doha','Qatar'),
('Kazachija, Kazachstanas','Kazachstano Respublika','KZ','KAZ','Astana','Kazakhstan'),
('Kenija','Kenijos Respublika','KE','KEN','Nairobis','Kenya'),
('Kinija','Kinijos Liaudies Respublika','CN','CHN','Pekinas','China'),
('Kipras','Kipro Respublika','CY','CYP','Nikosija','Cyprus'),
('Kirgizija, Kirgizstanas','Kirgizijos Respublika','KG','KGZ','Biškekas','Kyrgyzstan'),
('Kiribatis','Kiribačio Respublika','KI','KIR','Pietų Tarava','Kiribati'),
('Kolumbija','Kolumbijos Respublika','CO','COL','Bogota','Colombia'),
('Komorai','Komorų Sąjunga','KM','COM','Moronis','Comoros'),
('Kongas','Kongo Respublika','CG','COG','Brazavilis','Congo'),
('Kongo Demokratine Respublika','Kongo Demokratine Respublika','CD','COD','Kinšasa','Congo Democratic Republic'),
('Kosta Rika','Kosta Rikos Respublika','CR','CRI','San Chose','Costa Rica'),
('Kroatija','Kroatijos Respublika','HR','HRV','Zagrebas','Croatia'),
('Kuba','Kubos Respublika','CU','CUB','Havana','Cuba'),
('Kuveitas','Kuveito Valstybe','KW','KWT','Kuveitas','Kuwait'),
('Laosas','Laoso Liaudies Demokratine Respublika','LA','LAO','Vientianas','Lao People''s Democratic Republic'),
('Latvija','Latvijos Respublika','LV','LVA','Ryga','Latvia'),
('Lenkija','Lenkijos Respublika','PL','POL','Varšuva','Poland'),
('Lesotas','Lesoto Karalyste','LS','LSO','Maseru','Lesotho'),
('Libanas','Libano Respublika','LB','LBN','Beirutas','Lebanon'),
('Liberija','Liberijos Respublika','LR','LBR','Monrovija','Liberia'),
('Libija','Libijos Valstybe','LY','LBY','Tripolis','Libya'),
('Lichtenšteinas','Lichtenšteino Kunigaikštyste','LI','LIE','Vaducas','Liechtenstein'),
('Lietuva','Lietuvos Respublika','LT','LTU','Vilnius','Lithuania'),
('Liuksemburgas','Liuksemburgo Didžioji Hercogyste','LU','LUX','Liuksemburgas','Luxembourg'),
('Madagaskaras','Madagaskaro Demokratine Respublika','MG','MDG','Antananaryvas','Madagascar'),
('Malaizija','Malaizija','MY','MYS','Kvala Lumpūras','Malaysia'),
('Malavis','Malavio Respublika','MW','MWI','Lilongve','Malawi'),
('Maldyvai','Maldyvų Respublika','MV','MDV','Male','Maldives'),
('Malis','Malio Respublika','ML','MLI','Bamakas','Mali'),
('Malta','Maltos Respublika','MT','MLT','Valeta','Malta'),
('Marokas','Maroko Karalyste','MA','MAR','Rabatas','Morocco'),
('Maršalo Salos','Maršalo Salų Respublika','MH','MHL','Madžūras','Marshall Islands'),
('Mauricijus','Mauricijaus Respublika','MU','MUS','Port Luisas','Mauritius'),
('Mauritanija','Mauritanijos Islamo Respublika','MR','MRT','Nuakšotas','Mauritania'),
('Meksika','Meksikos Jungtines Valstijos','MX','MEX','Meksikas','Mexico'),
('Mianmaras, Birma','Mianmaro Sąjungos Respublika','MM','MMR','Neipidas','Myanmar'),
('Mikronezija','Mikronezijos Federacines Valstijos','FM','FSM','Palikyras','Micronesia'),
('Moldavija, Moldova','Moldovos Respublika','MD','MDA','Kišiniovas','Moldova'),
('Monakas','Monako Kunigaikštyste','MC','MCO','Monakas','Monaco'),
('Mongolija','Mongolija','MN','MNG','Ulan Batoras','Mongolia'),
('Mozambikas','Mozambiko Respublika','MZ','MOZ','Maputu','Mozambique'),
('Namibija','Namibijos Respublika','NA','NAM','Vindhukas','Namibia'),
('Naujoji Zelandija','Naujoji Zelandija','NZ','NZL','Velingtonas','New Zealand'),
('Nauru','Nauru Respublika','NR','NRU','Jarenas','Nauru'),
('Nepalas','Nepalo Federacine Demokratine Respublika','NP','NPL','Katmandu','Nepal'),
('Nyderlandai, Olandija','Nyderlandų Karalyste','NL','NLD','Amsterdamas','Netherlands'),
('Nigerija','Nigerijos Federacine Respublika','NG','NGA','Abudža','Nigeria'),
('Nigeris','Nigerio Respublika','NE','NER','Niamejus','Niger'),
('Nikaragva','Nikaragvos Respublika','NI','NIC','Managva','Nicaragua'),
('Norvegija','Norvegijos Karalyste','NO','NOR','Oslas','Norway'),
('Omanas','Omano Sultonatas','OM','OMN','Maskatas','Oman'),
('Pakistanas','Pakistano Islamo Respublika','PK','PAK','Islamabadas','Pakistan'),
('Palestina','Palestina','PS','PSE','Jaruzalė / Ramala','Palestine, State of'),
('Panama','Panamos Respublika','PA','PAN','Panama','Panama'),
('Papua Naujoji Gvineja','Papua Naujosios Gvinejos Nepriklausomoji Valstybe','PG','PNG','Port Morsbis','Papua New Guinea'),
('Paragvajus','Paragvajaus Respublika','PY','PRY','Asunsjonas','Paraguay'),
('Peru','Peru Respublika','PE','PER','Lima','Peru'),
('Pietų Afrika','Pietų Afrikos Respublika','ZA','ZAF','Pretorija / Keiptaunas','South Africa'),
('Pietų Koreja','Korejos Respublika','KR','KOR','Seulas','South Korea'),
('Pietų Sudanas','Pietų Sudano Respublika','SS','SSD','Džuba','South Sudan'),
('Portugalija','Portugalijos Respublika','PT','PRT','Lisabona','Portugal'),
('Prancūzija','Prancūzijos Respublika','FR','FRA','Paryžius','France'),
('Pusiaujo Gvineja','Pusiaujo Gvinejos Respublika','GQ','GNQ','Malabas','Equatorial Guinea'),
('Rytų Timoras','Rytų Timoro Demokratine Respublika','TL','TLS','Dìlis','Timor-Leste'),
('Ruanda','Ruandos Respublika','RW','RWA','Kigalis','Rwanda'),
('Rumunija','Rumunija','RO','ROU','Bukareštas','Romania'),
('Rusija','Rusijos Federacija','RU','RUS','Maskva','Russian Federation'),
('Sakartvelas, Gruzija','Sakartvelas','GE','GEO','Tbilìsis','Georgia'),
('Saliamono Salos','Saliamono Salos','SB','SLB','Honiara','Solomon Islands'),
('Salvadoras','Salvadoro Respublika','SV','SLV','San Salvadoras','El Salvador'),
('Samoa','Samoa Nepriklausomoji Valstybe','WS','WSM','Apija','Samoa'),
('San Marinas','San Marino Respublika','SM','SMR','San Marinas','San Marino'),
('San Tome ir Prinsipe','San Tome ir Prinsipes Demokratine Respublika','ST','STP','San Tomė','Sao Tome and Principe'),
('Saudo Arabija','Saudo Arabijos Karalyste','SA','SAU','Rijadas','Saudi Arabia'),
('Seišeliai','Seišelių Respublika','SC','SYC','Viktorija','Seychelles'),
('Senegalas','Senegalo Respublika','SN','SEN','Dakaras','Senegal'),
('Sent Kitsas ir Nevis','Sent Kitsas ir Nevis','KN','KNA','Basteras','Saint Kitts and Nevis'),
('Sent Lusija','Sent Lusija','LC','LCA','Kastris','Saint Lucia'),
('Sent Vinsentas ir Grenadinai','Sent Vinsentas ir Grenadinai','VC','VCT','Kingstaunas','Saint Vincent and the Grenadines'),
('Serbija','Serbijos Respublika','RS','SRB','Belgradas','Serbia'),
('Siera Leone','Siera Leones Respublika','SL','SLE','Fritaunas','Sierra Leone'),
('Singapūras','Singapūro Respublika','SG','SGP','Singapūras','Singapore'),
('Sirija','Sirijos Arabų Respublika','SY','SYR','Damaskas','Syrian Arab Republic'),
('Slovakija','Slovakijos Respublika','SK','SVK','Bratislava','Slovakia'),
('Slovenija','Slovenijos Respublika','SI','SVN','Liubliana','Slovenia'),
('Somalis','Somalio Federacine Respublika','SO','SOM','Mogadišas','Somalia'),
('Sudanas','Sudano Respublika','SD','SDN','Chartumas','Sudan'),
('Suomija','Suomijos Respublika','FI','FIN','Helsinkis','Finland'),
('Surinamas','Surinamo Respublika','SR','SUR','Paramaribas','Suriname'),
('Šiaures Koreja','Korejos Liaudies Demokratine Respublika','KP','PRK','Pchenjanas','Korea'),
('Šiaures Makedonija','Šiaures Makedojinos Respublika','MK','MKD','Skopjė','Republic of North Macedonia'),
('Šri Lanka','Šri Lankos Demokratine Socialistine Respublika','LK','LKA','Šri Džajavardanapura Kotė','Sri Lanka'),
('Švedija','Švedijos Karalyste','SE','SWE','Stokholmas','Sweden'),
('Šveicarija','Šveicarijos Konfederacija','CH','CHE','Bernas','Switzerland'),
('Tadžikija, Tadžikistanas','Tadžikistano Respublika','TJ','TJK','Dušanbė','Tajikistan'),
('Tailandas','Tailando Karalyste','TH','THA','Bankokas','Thailand'),
('Tanzanija','Tanzanijos Jungtine Respublika','TZ','TZA','Dodoma / Dar es Salamas','Tanzania, United Republic of'),
('Togas','Togo Respublika','TG','TGO','Lomė','Togo'),
('Tonga','Tongos Karalyste','TO','TON','Nukualofa','Tonga'),
('Trinidadas ir Tobagas','Trinidado ir Tobago Respublika','TT','TTO','Port of Speinas','Trinidad and Tobago'),
('Tunisas','Tuniso Respublika','TN','TUN','Tunisas','Tunisia'),
('Turkija','Turkijos Respublika','TR','TUR','Ankara','Turkey'),
('Turkmenija, Turkmenistanas','Turkmenistanas','TM','TKM','Ašchabadas','Turkmenistan'),
('Tuvalu','Tuvalu','TV','TUV','Funafutis','Tuvalu'),
('Uganda','Ugandos Respublika','UG','UGA','Kampala','Uganda'),
('Ukraina','Ukraina','UA','UKR','Kyjivas','Ukraine'),
('Urugvajus','Urugvajaus Rytų Respublika','UY','URY','Montevidejas','Uruguay'),
('Uzbekija, Uzbekistanas','Uzbekistano Respublika','UZ','UZB','Taškentas','Uzbekistan'),
('Vanuatu','Vanuatu Respublika','VU','VUT','Port Vila','Vanuatu'),
('Vatikanas','Vatikano Miesto Valstybe','VA','VAT','Šventasis Sostas','Holy See'),
('Venesuela','Venesuelos Bolivaro Respublika','VE','VEN','Karakasas','Venezuela'),
('Vengrija','Vengrija','HU','HUN','Budapeštas','Hungary'),
('Vietnamas','Vietnamo Socialistine Respublika','VN','VNM','Hanojus','Viet Nam'),
('Vokietija','Vokietijos Federacine Respublika','DE','DEU','Berlynas','Germany'),
('Zambija','Zambijos Respublika','ZM','ZMB','Lusaka','Zambia'),
('Zimbabve','Zimbabves Respublika','ZW','ZWE','Hararė','Zimbabwe'),
('Žaliasis Kyšulys','Žaliojo Kyšulio Respublika','CV','CPV','Praja','Cabo Verde');

UPDATE public.salys SET search = replace(array_to_string(ARRAY(SELECT DISTINCT word FROM unnest(string_to_array(ar.unaccent(lower(CONCAT(name,' ',title,' ',capital,' ',eng,' ',iso2,' ',iso3))), ' ')) AS word), ' '),'  ',' ');
UPDATE public.salys SET eu=true WHERE iso3 in ('AUT','BEL','BGR','CYP','CZE','DEU','DNK','ESP','EST','FIN','FRA','GRC','HRV','HUN','IRL','ITA','LTU','LUX','LVA','MLT','NLD','POL','PRT','ROU','SVK','SVN','SWE');

CREATE OR REPLACE VIEW public.v_app_salys AS SELECT iso3 "Iso3", iso2 "Iso2", name "Pavad", title "Pilnas", capital "Sostine", eng "Eng", eu "Eu", search FROM public.salys;

CREATE INDEX salys_iso2_idx ON public.salys (iso2);
CREATE INDEX salys_search_idx ON public.salys USING gin(search gin_trgm_ops);


GRANT SELECT ON public.salys TO "registrai_app";
GRANT SELECT ON public.v_app_salys TO "registrai_app";

